/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.andriawan.event_tix.pages.fragments.home;

import com.andriawan.event_tix.repository.EventRepository;
import javax.swing.JOptionPane;

/**
 *
 * @author naufalfawwaz
 */
public class EventForm extends javax.swing.JPanel {
    
    EventRepository repository;

    /**
     * Creates new form EventForm
     */
    public EventForm() {
        initComponents();
        repository = new EventRepository();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSignIn = new com.k33ptoo.components.KButton();
        jLabel5 = new javax.swing.JLabel();
        inputWaktu = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputJudul = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputDeskripsi = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        inputKuota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputHarga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        inputTipe = new javax.swing.JComboBox<>();
        btnSignIn1 = new com.k33ptoo.components.KButton();

        btnSignIn.setText("Sign In");
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignIn.setkBackGroundColor(new java.awt.Color(42, 119, 191));
        btnSignIn.setkBorderRadius(25);
        btnSignIn.setkEndColor(new java.awt.Color(2, 54, 102));
        btnSignIn.setkHoverEndColor(new java.awt.Color(32, 103, 169));
        btnSignIn.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        btnSignIn.setkHoverStartColor(new java.awt.Color(42, 119, 191));
        btnSignIn.setkSelectedColor(new java.awt.Color(42, 119, 191));
        btnSignIn.setkStartColor(new java.awt.Color(32, 103, 169));
        btnSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignInMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tipe");

        inputWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputWaktuActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(2, 54, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Tambah Event");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Waktu (format. yyyy-mm-dd HH:MM:ss");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Deskripsi");

        inputJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJudulActionPerformed(evt);
            }
        });

        inputDeskripsi.setColumns(20);
        inputDeskripsi.setRows(5);
        jScrollPane1.setViewportView(inputDeskripsi);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Judul");

        inputKuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKuotaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Kuota");

        inputHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputHargaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Harga");

        inputTipe.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        inputTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "paid", "free" }));
        inputTipe.setToolTipText("");
        inputTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipeActionPerformed(evt);
            }
        });

        btnSignIn1.setText("Simpan Event");
        btnSignIn1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSignIn1.setkBackGroundColor(new java.awt.Color(42, 119, 191));
        btnSignIn1.setkBorderRadius(12);
        btnSignIn1.setkEndColor(new java.awt.Color(2, 54, 102));
        btnSignIn1.setkHoverEndColor(new java.awt.Color(32, 103, 169));
        btnSignIn1.setkHoverForeGround(new java.awt.Color(204, 204, 255));
        btnSignIn1.setkHoverStartColor(new java.awt.Color(42, 119, 191));
        btnSignIn1.setkSelectedColor(new java.awt.Color(42, 119, 191));
        btnSignIn1.setkStartColor(new java.awt.Color(32, 103, 169));
        btnSignIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignIn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputKuota, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(inputTipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(inputWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSignIn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputKuota, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSignIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputWaktuActionPerformed

    private void inputJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJudulActionPerformed

    private void inputKuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKuotaActionPerformed

    private boolean validateInput() {
        boolean valid = true;

        String judul = inputJudul.getText().trim();
        String kuota = inputKuota.getText().trim();
        String tipe = (String) inputTipe.getSelectedItem();
        String harga = inputHarga.getText().trim();
        String waktu = inputWaktu.getText().trim();
        String desk = inputDeskripsi.getText().trim();

        if (judul.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan isi judul");
            valid = false;
        }
        
        if (kuota.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Silahkan isi kuota");
            valid = false;
        }

        return valid;
    }
    
    private void inputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputHargaActionPerformed

    private void inputTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipeActionPerformed

    private void btnSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignInMouseClicked

        if (validateInput()) {
            String judul = inputJudul.getText().trim();
            String kuota = inputKuota.getText().trim();
            String tipe = (String) inputTipe.getSelectedItem();
            String harga = inputHarga.getText().trim();
            String waktu = inputWaktu.getText().trim();
            String desk = inputDeskripsi.getText().trim();

            if (repository.addEvent(judul, desk, Integer.valueOf(kuota), tipe, Integer.valueOf(harga), waktu)) {
                JOptionPane.showMessageDialog(null, "Berhasil menambahkan data event");
                inputJudul.setText("");
                inputKuota.setText("");
                inputTipe.setSelectedIndex(0);
                inputHarga.setText("");
                inputWaktu.setText("");
                inputDeskripsi.setText("");
            }
        }
    }//GEN-LAST:event_btnSignInMouseClicked

    private void btnSignIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignIn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignIn1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btnSignIn;
    private com.k33ptoo.components.KButton btnSignIn1;
    private javax.swing.JTextArea inputDeskripsi;
    private javax.swing.JTextField inputHarga;
    private javax.swing.JTextField inputJudul;
    private javax.swing.JTextField inputKuota;
    private javax.swing.JComboBox<String> inputTipe;
    private javax.swing.JTextField inputWaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
